# Generated by Django 3.1.7 on 2021-03-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210222_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codeRegistro',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
